version: '3.9'

services:
  web:
    container_name: nginx_omeglit
    image: "nginx:stable"
    security_opt:
      - no-new-privileges
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ~/omeglit_${TARGET}/secrets:/opt/omeglit/secrets:ro
      - ./docker/${TARGET}/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/omeglit_${TARGET}/certbot/www:/var/www/certbot/:ro
    ports:
      - "80:80"
      - "443:443"
#    environment:
#      - NGINX_HOST=${DOMAIN}
#      - NGINX_PORT=80
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  nodejs:
    container_name: nodejs_omeglit
    image: "node:16-alpine"
    security_opt:
      - no-new-privileges
    volumes:
      - ~/omeglit_${TARGET}/secrets:/opt/omeglit/secrets:ro
    ports:
      - "${WS_PORT}:8080"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: ${TARGET}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  certbot_cf:
    container_name: certbot_omeglit
    image: "certbot/dns-cloudflare"
    security_opt:
      - no-new-privileges
    volumes:
      - ~/omeglit_${TARGET}/secrets:/etc/letsencrypt/live
      - ~/omeglit_${TARGET}/certbot/www/:/var/www/certbot/:rw
      - ./cloudflare.ini:/root/cloudflare.ini:ro